name: xcollection-dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - codecov
  - coverage
  - dask
  - distributed
  - esmpy
  - flake8
  - git
  - intake
  - intake-xarray
  - ipykernel
  - isort
  - make
  - nbsphinx
  - netcdf4
  - numpy
  - numpydoc
  - pytest
  - pytest-cov
  - python=3.7
  - recommonmark
  - sphinx_rtd_theme
  - sphinx>=1.6
  - tqdm
  - xarray>=0.11.3
  - xesmf
  - zarr
  - pip:
    - sphinx_copybutton
    - git+https://github.com/NCAR/esmlab.git
    - git+https://github.com/NCAR/intake-esm.git
